runtime: nodejs16

instance_class: F2

handlers:
  - url: /
    static_files: dist/beautypro-frontend/index.html
    upload: dist/beautypro-frontend/index.html

  - url: /
    static_dir: dist/beautypro-frontend
